#!/usr/bin/env python3
import sys
import os
import logging

GAMESYNC_DEBUG = 'GAMESYNC_DEBUG'


def is_env_var(arg):
    return "=" in arg


def wrap_process():
    input_command = sys.argv[1:]
    original_command = ' '.join(input_command)
    logging.debug(f'The original command: {original_command}')


if __name__ == '__main__':
    DEBUG = os.getenv(GAMESYNC_DEBUG)
    log_file = None
    if DEBUG == 'true':
        log_file = f'{os.path.expanduser("~")}/.local/share/gamesync/log.log'

    logging.basicConfig(
        filename=log_file,
        filemode='a',
        format='%(asctime)s | %(levelname)s | %(message)s',
        level=logging.NOTSET,
        datefmt='%Y-%m-%d %H:%M:%S')
    wrap_process()

